#!/bin/bash

# activate conda environment
source /home/waves/anaconda3/etc/profile.d/conda.sh
conda activate MATS_img

# main path
MATS_dir='/home/waves/projects/MATS/'

# options 
level="1b"
version="0.4"
snippet="True"

# output mainly for naming
dates=$(date -d '2023-02-08' +'%Y_%m_%d')
outdir=${MATS_dir}'animations/daily/'$dates'/'

# measurement date for naming
measurements_date="$(date -d '2023-02-08' +'%Y-%m-%d')"

# output
#dates=$(date -d '-0 days' +'%Y_%m_%d')
#outdir=${MATS_dir}'animations/daily/'$dates'/'

# measurement date
#measurements_date="$(date -d '-3 days' +'%Y-%m-%d')"

# initiate
echo -e "DAILY ANIMATION (${dates}): Initiating ..."
echo 'MATS DATA: L'${level}' data (v'${version}')..'
echo 'Generating figures in: '${outdir}

# merge video parts based on list
file="${outdir}daily_${dates}.mp4"
# { ffmpeg -f concat -safe 0 -i ${txt_file} -c copy ${file}; }

# upload video
contact="bjorn.linder@misu.su.se / olemartin.christensen@misu.su.se"
description="Autogenerated timelapse of MATS L${level} data (v${version}) from ${measurements_date}. Contact: ${contact}"

{ python ${MATS_dir}MATS-utility-functions/src/mats_utils/daily_preview/upload.py --file="${file}" --title="MATS L${level}: ${measurements_date}" --description="${description}" --keywords="MATS" --category="22" --privacyStatus="private"; }

echo 'End of program .....'